### PR TITLE
Make ReactiveMongoComponents truely compile-time injectable

### PR DESCRIPTION
**Pull request by avdv**
As already promised by the documentation on the ReactiveMongo web site,
make the ReactiveMongoComponents trait useful with compile time
dependency injection.

### CODE REVIEW

**Comment by cchantep** [comment]
Sorry, but for me this PR is not compatible with the goal of being able to have a custom impl of `ReactiveMongoApi` in a controller, even if the default one is used with the automatic injection.

**Comment by avdv** [comment]
> Sorry, but for me this PR is not compatible with the goal of being able to have a custom impl of ReactiveMongoApi in a controller

Why? There's nothing stopping you from doing that. You have the same possibilities as before, plus a proper `ReactiveMongoComponents` implementation, which is currently just lacking / non-working.

In the ReactiveMongo documentation (http://reactivemongo.org/releases/0.11/documentation/tutorial/play2.html) is suggested that one could use the `ReactiveMongoComponents` trait for compile time dependency injection, but that's just bogus.  I'm only trying to adjust the code to the docs and to how the rest of Play regarding compile time injection is supposed to work, IMO.

**Comment by cchantep** [comment]
What's non-working with the current controller, used for example with no issue in the sample apps?

**Comment by avdv** [comment]
> What's non-working with the current controller, used for example with no issue in the sample apps?

The compile-time dependency injection is non-working because it is not implemented. Look at the example for the so-called "compile-time dependency injection" from the documentation:

```scala
import javax.inject.Inject

class MyController @Inject() (val reactiveMongoApi: ReactiveMongoApi)
    extends Controller with MongoController with ReactiveMongoComponents {

}
```

There's no compile-time dependency injection going on here, as the ReactiveMongoApi is still injected using the DI framework at runtime. That makes no sense.

**Comment by cchantep** [comment]
The compile-time dependency declaration , that can be combine with DI to make it safer, is different from inheritance or default impl. That's the way it currently provided. This issue tracker is not the place to discuss about this subject (moreover not specific to ReactiveMongo). I suggest you have a look at the Play documentation about that, and possibly discuss on the user MailingList. Best regards.

**Pull request closed without merging**
