### PR TITLE
update to support maxTimeMS

### PR DESCRIPTION
**Pull request by fr3akX**
Update to support https://github.com/ReactiveMongo/ReactiveMongo/pull/399

### CODE REVIEW

**Comment by fr3akX** [comment]
tests will succeed when ReactiveMongo snapshot is published

**Comment by cchantep** [comment]
Hi @fr3akX , you need to rebase against master to have the snapshot resolver from #161 . Best regards

**Comment by fr3akX** [comment]
@cchantep rebased, but still uses wrong lib

**Comment by cchantep** [comment]
Needs a new rebase

**Pull request closed without merging**
