### PR TITLE
Update to Scala 2.12

### PR DESCRIPTION
**Pull request by cchantep**

### CODE REVIEW

**Comment by ankeshdave** [comment]
@cchantep 
Any Plans to upgrade this to Scala 2.12 ??

**Comment by cchantep** [comment]
It depends on the whole ecosystem being compatible with 2.12

**Comment by FabioPinheiro** [comment]
I have some questions about how to build the project for Scala 2.12 and play 2.6.0-M5, from the master branch.
If I do "sbt publish-local" it will only publish "play2-reactivemongo_2.11"
By the away in Play2-ReactiveMongo.scala you have the key crossScalaVersions two-time:
crossScalaVersions := Seq("2.11.8", "2.12.1")
crossScalaVersions := Seq(scalaVersion.value) //scalaVersion := "2.11.8"

**Comment by cchantep** [comment]
Hi,

Please rather use the [MailingList](https://groups.google.com/forum/m/?fromgroups#!forum/reactivemongo) to ask questions/for help (rather than this issue/feature tracker).

> BTW such questions are not specific to ReactiveMongo, but rather SBT related, do better to ask on [SO](http://stackoverflow.com/questions/tagged/scala).

The Scala 2.12 artefact will be officially available for next minor 0.12.4, meanwhile a snapshot wilk be available. 

Best regards

**Pull request merged**
