### PR TITLE
Favor Integer and Long over Double during serialization to BSON

### PR DESCRIPTION
**Pull request by thibaultdelor**
I haven't even try to compile it, I have some dependencies issues with sbt.

### CODE REVIEW

**Comment by cchantep** [comment]
Hi, as for priority check, I would do it this following order:

- 1. `n.isDecimalDouble` | `n.isDecimalFloat` => `BSONDouble`
- 2. `n.isValidLong` => `BSONLong`
- 3. `n.isValidInt` => `BSONInteger`

**Comment by vallu751** [comment]
@cchantep, all numbers that would pass step 3 would also pass steps 1 and 2. And all numbers that would pass step 2 would also pass step 1.

In other words, we would have BSONDoubles always. Just like we have now.

**Comment by cchantep** [comment]
If `!n.isWhole`, then `BSONDouble`, else `BSONLong` (if `n.isValidLong`) or `BSONInteger` (if `n.isValidInt`).

**Comment by vallu751** [comment]
That's closer. Although integers would still become longs. Unfortunately that would not solve the issue I pointed out in my comment on Oct 24. Let me elaborate. Currently saving the following JSON:

{
  "integer" : 1,
  "doubleOne" : 1.5,
  "doubleTwo" : 2.0
}

Will result in:

{
  "integer" : 1.0,
  "doubleOne" : 1.5,
  "doubleTwo" : 2.0
}

This leads to problems e.g. when deserializing from BSON: doc.getAs[Int]("int") will result in None.
With the proposed solutions we would get:

{
  "integer" : 1,
  "doubleOne" : 1.5,
  "doubleTwo" : 2
}

Which would similarly break the "doubleTwo" field. Any time a double happens to be a whole number, it's type would change during runtime.

**Comment by cchantep** [comment]
With the latest ulo check, the case `2.0` should be handled as double.

**Comment by cchantep** [comment]
With following read function:

```scala
  val numberReads: PartialFunction[JsValue, JsResult[BSONValue]] = {
    case JsNumber(n) if !n.ulp.isWhole => JsSuccess(BSONDouble(n.toDouble))    
    case JsNumber(n) if n.isValidInt   => JsSuccess(BSONInteger(n.toInt))
    case JsNumber(n) if n.isValidLong  => JsSuccess(BSONLong(n.toLong))
  }
```

Conversions are done like:

```
scala> numberReads(JsNumber(BigDecimal("2.0")))
res1: play.api.libs.json.JsResult[reactivemongo.bson.BSONValue] = JsSuccess(BSONDouble(2.0),)

scala> numberReads(JsNumber(BigDecimal("1")))
res2: play.api.libs.json.JsResult[reactivemongo.bson.BSONValue] = JsSuccess(BSONInteger(1),)

scala> numberReads(JsNumber(BigDecimal("1.5")))
res3: play.api.libs.json.JsResult[reactivemongo.bson.BSONValue] = JsSuccess(BSONDouble(1.5),)

scala> numberReads(JsNumber(BigDecimal(Long.MaxValue)))
res4: play.api.libs.json.JsResult[reactivemongo.bson.BSONValue] = JsSuccess(BSONLong(9223372036854775807),)
```

**Comment by vallu751** [comment]
I stand corrected, the solution looks great to me :+1:

**Comment by cchantep** [comment]
(See #116)

**Comment by cchantep** [comment]
Backport branch available for manual build at https://github.com/cchantep/Play-ReactiveMongo/tree/backport-116

**Pull request closed without merging**
