### PR TITLE
Play 2.4 support

### PR DESCRIPTION
**Pull request by cchantep**

### CODE REVIEW

**Comment by mrkaspa** [comment]
I need this urgent

**Comment by Reeebuuk** [comment]
me2

**Comment by cchantep** [comment]
The snapshot `"org.reactivemongo" %% "play2-reactivemongo" % "0.11.0.play24-SNAPSHOT"` is available on [OSS snapshots](https://oss.sonatype.org/content/repositories/snapshots/org/reactivemongo/play2-reactivemongo_2.11/0.11.0.play24-SNAPSHOT/).

**Comment by francisdb** [comment]
@Reeebuuk there is a snapshot available

```scala
  val reactivemongoVersion = "0.11.0-SNAPSHOT"
  val play2ReactivemongoVersion = "0.11.0.play24-SNAPSHOT"
...
  "org.reactivemongo" %% "reactivemongo" % reactivemongoVersion,
  "org.reactivemongo" %% "play2-reactivemongo" % play2ReactivemongoVersion,
...
// TODO remove once reactivemongo is released
  Resolver.sonatypeRepo("snapshots")
```

**Comment by Reeebuuk** [comment]
Thx guys for the fast response. Will try it out :+1:

**Comment by cchantep** [comment]
It's not recommanded to specify both the driver and plugin dependencies. It can lead to have a driver dependency not matching requirement of the plugin, which is the case in @francisdb example, as the updated 0.11.0.play24-SNAPSHOT plugin requires the driver 0.11.0-M2.

Just add the plugin dependency and let SBT resolving the transitive dependencies.

**Comment by cchantep** [comment]
The milestone plugin is now available on Maven central as `"org.reactivemongo" %% "play2-reactivemongo" % "0.11.0.play24-M2"`.

This PR will be merged after some documentation work (no API/impl change between this M2 and the final release at end of the week).

The already updated documentation is available [there](https://github.com/cchantep/Play-ReactiveMongo/blob/play24/README.md).

**Comment by francisdb** [comment]
Big thanks @cchantep !

**Pull request merged**
